Portfolio project: header section(only mobile)
bekjon-me/microverse pull request #3
Opened 2022-05-26 18:53 UTC by bekjon-me

In this milestone:

- added navigation menu
- added headline section

2022-05-26 18:57 UTC, bekjon-me commented
@omar-mohamad

2022-05-26 18:59 UTC, bekjon-me commented
@Omar-Muhamad

2022-05-26 20:38 UTC, omarsalem7 requested changes
Hi @bekjon-me, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)


## Highlights
- Descriptive pull request ✔️
- Stick to design ✔️
- The content is aligned with flexbox ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 20:38 UTC, omarsalem7 commented on README.md
> +> Description the project.
- [ ] Kindly add the description for the project.

2022-05-26 20:38 UTC, omarsalem7 commented on index.html
> +    </nav>
- [ ] Kindly consider the container of the section is a `header` tag
- [ ] Consider your hamburger button has a nav tag to improve SEO for your website, you can read more from [here](https://developer.mozilla.org/en-US/docs/Glossary/Semantics)

2022-05-26 20:38 UTC, omarsalem7 commented on index.html
> +    <header>
- [ ] the headline section (after the header) and should be `<section>` to improve SEO.

2022-05-26 20:38 UTC, omarsalem7 commented on index.html
> +      />
- [ ] you made a great work to match the design but it will be better to remove the image and use the CSS property `background-img` .

2022-05-26 20:38 UTC, omarsalem7 commented on index.html
> +        </h2>
- [ ] The main title should be `h1` tag to make your website accessible for all people.

2022-05-26 20:38 UTC, omarsalem7 commented on index.html
> +            </li>
- [ ] Consider each icon has a link `a` tag wrap the img tag

2022-05-27 04:15 UTC, merged

2022-05-27 05:30 UTC, Ginohmk reviewed
Hi @bekjon-me , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![keep-trying-youre-almost-there](https://user-images.githubusercontent.com/67087664/169483884-c624db70-793d-42be-8ebe-afef6a1cd5c3.gif)

 ## Highlights
- Linter all green :100: 
- Good commit message :100: 
- Good PR summary message :1st_place_medal: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

**Please next time do not merge a Pull request, unless it as being approved by a reviewer, Thanks** :+1: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 05:30 UTC, Ginohmk commented on index.html
> +      />
- Please as the previous reviewer suggested, make use of the CSS background-image property, to please this image as a background image.

2022-05-27 05:30 UTC, Ginohmk commented on index.html
> +        </h2>
- Please as suggested by the previous reviewer, change the `<h2>` tag to an `<h1>`, as this make your HTML code more sematic

2022-05-27 05:30 UTC, Ginohmk commented on index.html
> +            </li>
- Please place `<img>` tag inside a link `<a>` as it is suppose to be a link to your social media account base on the icon clicked. See example bellow
```html
<ul>
  <li> <a href = "#" target = "_blank"> <img src="/elements/gthb.png" alt="github"> </a></li>
  <li> <a href = "#" target = "_blank"> <img src="/elements/lnkin.png" alt="linkedin"></a></li>
  <li> <a href = "#" target = "_blank"> <img src="/elements/twtr.png" alt="twitter"> </a></li>
  <li> <a href = "#" target = "_blank"><img src="/elements/m.png" alt="m"></a></li>
  <li> <a href = "#" target = "_blank"> <img src="/elements/chill.png" alt="chill"> </a></li>
</ul>
```

2022-05-27 05:30 UTC, Ginohmk commented on index.html
> +    <header>
- Please change the `<header>` tag to a `<section>`, in other to make your HTML more sematic and help with SEO(Search Engine Optimization).

2022-05-27 05:30 UTC, Ginohmk commented on index.html
> +    </nav>
- For example
```html
<header>
     <nav class="nav">
      <div class="logo">
        <img src="./src/assets/icons/My_Logo.svg" alt="Logo" />
      </div>
      <div class="hamburger-menu">
        <img src="./src/assets/icons/Icon_Menu.svg" alt="Hamburger menu" />
      </div>
    </nav>
</header>
```